export const BASE_URL = 'https://stapi.co/api/v1/rest/';

export const LOCAL_STORAGE = {
  lastSearch: 'last-search',
};

export const ITEMS = {
  animal: 'animals',
  astronomicalObject: 'astronomical objects',
  bookCollection: 'book collections',
  book: 'books',
  bookSeries: 'book series',
  comics: 'comics',
  conflict: 'conflicts',
  character: 'characters',
  comicCollection: 'comic collections',
  company: 'companies',
  comicSeries: 'comic series',
  comicStrip: 'comic strips',
  element: 'elements',
  episode: 'episodes',
  food: 'foods',
  literature: 'literature pieces',
  location: 'locations',
  magazine: 'magazines',
  medicalCondition: 'medical conditions',
  movie: 'movies',
  magazineSeries: 'magazine series',
  material: 'materials',
  occupation: 'occupations',
  organization: 'organizations',
  performer: 'performers',
  season: 'seasons',
  spacecraftClass: 'spacecraft classes',
  series: 'series',
  soundtrack: 'soundtracks',
  species: 'species',
  spacecraft: 'spacecrafts',
  staff: 'staff members',
  tradingCard: 'trading cards',
  technology: 'technology pieces',
  title: 'titles',
  tradingCardDecks: 'trading card decks',
  tradingCardSet: 'trading card sets',
  videoGame: 'video games',
  videoRelease: 'video releases',
  weapon: 'weapons',
};
