export const BASE_URL = 'https://stapi.co/api/v1/rest/';

export const LOCAL_STORAGE = {
  lastSearch: 'last-search',
};

export const ITEMS = {
  animals: 'animals',
  astronomicalObjects: 'astronomical objects',
  bookCollections: 'book collections',
  books: 'books',
  bookSeries: 'book series',
  comics: 'comics',
  conflicts: 'conflicts',
  characters: 'characters',
  comicCollections: 'comic collections',
  companies: 'companies',
  comicSeries: 'comic series',
  comicStrips: 'comic strips',
  elements: 'elements',
  episodes: 'episodes',
  foods: 'foods',
  literaturePieces: 'literature pieces',
  locations: 'locations',
  magazines: 'magazines',
  medicalConditions: 'medical conditions',
  movies: 'movies',
  magazineSeries: 'magazine series',
  materials: 'materials',
  occupations: 'occupations',
  organizations: 'organizations',
  performers: 'performers',
  seasons: 'seasons',
  spacecraftClasses: 'spacecraft classes',
  series: 'series',
  soundtracks: 'soundtracks',
  species: 'species',
  spacecrafts: 'spacecrafts',
  staffMembers: 'staff members',
  tradingCards: 'trading cards',
  technologyPieces: 'technology pieces',
  titles: 'titles',
  tradingCardDecks: 'trading card decks',
  tradingCardSets: 'trading card sets',
  videoGames: 'video games',
  videoReleases: 'video releases',
  weapons: 'weapons',
};
